version: 2.1
jobs:
  cypress:
    docker:
      - image: circleci/node:lts-browsers
    steps:
      - checkout
      - restore_cache:
          keys:
            - allianz-tests-{{ checksum ".tests/yarn.lock" }}
            - allianz-tests-
      - run: cd .tests && yarn
      - run: cd .tests && yarn test --config video=false
      - save_cache:
          key: allianz-tests-{{ checksum ".tests/yarn.lock" }}
          paths:
            - ~/.tests/node_modules
