version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:4.8.2
    steps:
      - run: sudo apt-get update
      - run: sudo apt-get install openjdk-7-jre-headless
      - run: wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.0.tgz
      - run: tar xf apache-jmeter-5.0.tgz
      - checkout
      - run: cd apache-jmeter-5.0/bin/./jmeter.sh -n -t functional_test.jmx
      - run: cd apache-jmeter-5.0/bin/./jmeter.sh -n -t non_functional_test.jmx
